name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    # At 03:00 PM (UTC)
    - cron: "0 15 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUILD_PATH: "." # default value when not using subfolders

jobs:
  run:
    name: Build and Run jar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run build and execute with Gradle wrapper
        id: gradle
        working-directory: ./
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          ./gradlew build  # Build the project and produce the JAR
          java -jar build/libs/Apollointhehouse-Web-1.0-SNAPSHOT.jar ${{ env.PAT }} # Run the JAR

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: './out'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: run
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4