name: Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

env:
  BUILD_PATH: "." # default value when not using subfolders

jobs:
  run:
    name: Build Static Site and Run JAR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run build and execute with Gradle wrapper
        id: gradle
        working-directory: ./
        run: |
          ./gradlew build  # Build the project and produce the JAR
          java -jar build/libs/Apollointhehouse-Web-1.0-SNAPSHOT.jar  # Run the JAR (make sure the path matches)

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
        with:
          build-dir: './out'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: run
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: './out'
